### ISSUE TITLE
SROS Rootifier or how to flatten 7750 SR config

### ISSUE THREAD

**Issue by hellt** [hellt/netdevops.me_gitment_comments#40]
https://netdevops.me/2017/sros-rootifier-or-how-to-flatten-7750-sr-config/ 

 Back in the days when I mostly did routing stuff I spent the whole day configuring SROS devices via SSH. And once in a while I saw that SSH session or its server part (or even underlying connection) glitched, resulting in a corrupted lines feeded to the device.

What was also quite common is to make a mistake (i.e. syntax one) in a single line and watch like the rest of config got applied to the wrong context.

These sad facts pushed me to create a rootifier CLI script, that was converting tree-like SROS config into flattented (aka rooted) fashion.

Now I decided to make a web service of that script, that is publicly available at https://rootifier.netdevops.me/

**Comment by basondole** [comment]
Hi

The link does not work @ https://rootifier.netdevops.me/

**Comment by hellt** [comment]
> @basondole
> Hi
> 
> The link does not work @ https://rootifier.netdevops.me/

thanks.
should be fixed now

**Comment by basondole** [comment]
Hi

Still doesn't load up, tried different browser but same fate

**Comment by arsalkeen** [comment]
Use it with http instead of https :)
http://rootifier.netdevops.me/

**Comment by arsalkeen** [comment]
> @basondole
> Hi
> 
> Still doesn't load up, tried different browser but same fate

Use it with http instead of https :)
http://rootifier.netdevops.me/
